import Foundation

public final class CMUDICTStore {
    public static let shared = CMUDICTStore()
    
    public let phonemesByWord: [String: [String]]
    
    public init() {
        phonemesByWord = [
            "i": ["AY1"],
            "write": ["R", "AY1", "T"],
            "at": ["AE1", "T"],
            "night": ["N", "AY1", "T"],
            "when": ["W", "EH1", "N"],
            "the": ["DH", "AH0"],
            "light": ["L", "AY1", "T"],
            "goes": ["G", "OW1", "Z"],
            "low": ["L", "OW1"],
            "fight": ["F", "AY1", "T"],
            "inside": ["IH2", "N", "S", "AY1", "D"],
            "starts": ["S", "T", "AA1", "R", "T", "S"],
            "to": ["T", "UW1"],
            "show": ["SH", "OW1"],
            "pace": ["P", "EY1", "S"],
            "room": ["R", "UW1", "M"],
            "slow": ["S", "L", "OW1"],
            "and": ["AH0", "N", "D"],
            "tight": ["T", "AY1", "T"],
            "trying": ["T", "R", "AY1", "IH0", "NG"],
            "rhyme": ["R", "AY1", "M"],
            "my": ["M", "AY1"],
            "way": ["W", "EY1"],
            "through": ["TH", "R", "UW1"],
            "dawn": ["D", "AO1", "N"],
            "feels": ["F", "IY1", "L", "Z"],
            "far": ["F", "AA1", "R"],
            "away": ["AH0", "W", "EY1"],
            "stay": ["S", "T", "EY1"],
            "awake": ["AH0", "W", "EY1", "K"],
            "till": ["T", "IH1", "L"],
            "break": ["B", "R", "EY1", "K"],
            "of": ["AH1", "V"],
            "day": ["D", "EY1"],
            "mind": ["M", "AY1", "N", "D"],
            "rewinds": ["R", "IY0", "W", "AY1", "N", "D", "Z"],
            "what": ["W", "AH1", "T"],
            "might": ["M", "AY1", "T"],
            "say": ["S", "EY1"],
            "another": ["AH0", "N", "AH1", "DH", "ER0"],
            "line": ["L", "AY1", "N"],
            "time": ["T", "AY1", "M"],
            "climb": ["K", "L", "AY1", "M"],
            "thought": ["TH", "AO1", "T"],
            "clock": ["K", "L", "AA1", "K"],
            "won't": ["W", "OW1", "N", "T"],
            "stop": ["S", "T", "AA1", "P"],
            "keeps": ["K", "IY1", "P", "S"],
            "its": ["IH1", "T", "S"],
            "chase": ["CH", "EY1", "S"],
            "sound": ["S", "AW1", "N", "D"],
            "left": ["L", "EH1", "F", "T"],
            "behind": ["B", "IH0", "HH", "AY1", "N", "D"],
            "erase": ["IH0", "R", "EY1", "S"],
            "trace": ["T", "R", "EY1", "S"],
            "phrase": ["F", "R", "EY1", "Z"],
            "aligns": ["AH0", "L", "AY1", "N", "Z"],
            "each": ["IY1", "CH"],
            "verse": ["V", "ER1", "S"],
            "curse": ["K", "ER1", "S"],
            "sign": ["S", "AY1", "N"],
            "good": ["G", "UH1", "D"],
            "words": ["W", "ER1", "D", "Z"],
            "arrive": ["ER0", "AY1", "V"],
            "walk": ["W", "AO1", "K"],
            "block": ["B", "L", "AA1", "K"],
            "echoes": ["EH1", "K", "OW0", "Z"],
            "bounce": ["B", "AW1", "N", "S"],
            "step": ["S", "T", "EH1", "P"],
            "take": ["T", "EY1", "K"],
            "rhythm": ["R", "IH1", "DH", "AH0", "M"],
            "counts": ["K", "AW1", "N", "T", "S"],
            "around": ["AH0", "R", "AW1", "N", "D"],
            "begins": ["B", "IH0", "G", "IH1", "N", "Z"],
            "mount": ["M", "AW1", "N", "T"],
            "beat": ["B", "IY1", "T"],
            "breath": ["B", "R", "EH1", "TH"],
            "right": ["R", "AY1", "T"],
            "amount": ["AH0", "M", "AW1", "N", "T"],
            "hear": ["HH", "IH1", "R"],
            "streets": ["S", "T", "R", "IY1", "T", "S"],
            "repeat": ["R", "IY0", "P", "IY1", "T"],
            "tone": ["T", "OW1", "N"],
            "cracked": ["K", "R", "AE1", "K", "T"],
            "up": ["AH1", "P"],
            "microphone": ["M", "AY1", "K", "R", "AH0", "F", "OW2", "N"],
            "speak": ["S", "P", "IY1", "K"],
            "heat": ["HH", "IY1", "T"],
            "not": ["N", "AA1", "T"],
            "alone": ["AH0", "L", "OW1", "N"],
            "city": ["S", "IH1", "T", "IY0"],
            "hums": ["HH", "AH1", "M", "Z"],
            "flesh": ["F", "L", "EH1", "SH"],
            "bone": ["B", "OW1", "N"]
        ]
    }
    
    public func phonemes(for word: String) -> [String]? {
        phonemesByWord[word.lowercased()]
    }
}
